### ISSUE TITLE
[CI/CD][Nordic] 研究下CI CD 机器人如何使用

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#102]

**Comment by supperthomas** [comment]
需要添加nordic相关的bsp的自动化编译。

**Comment by supperthomas** [comment]
https://www.ruanyifeng.com/blog/2012/08/blogging_with_jekyll.html

**Comment by supperthomas** [comment]
https://www.bilibili.com/video/BV1244y1r7Yg?from=search&seid=17073391601487871488&spm_id_from=333.337.0.0

**Comment by chenyingchun0312** [comment]
https://www.r2coding.com/

https://mp.weixin.qq.com/s/PgoXJcJX_sm5132VGQoZ1w

**Comment by supperthomas** [comment]
DONE
