### ISSUE TITLE
[doc] Typora 使用gitee图床

### ISSUE THREAD

**Issue by chenyingchun0312** [supperthomas/supperthomas_doc#118]
可以实现WIKI和CSDN上同步发布文档，不修改任何图片路径

**Comment by chenyingchun0312** [comment]
https://supperthomas-wiki.readthedocs.io/en/latest/WIKI_FAQ/03/markdown_faq.html

**Comment by supperthomas** [comment]
![图片](https://user-images.githubusercontent.com/60349489/162470400-2efce9cd-3df8-43e0-bf57-b600e15d5809.png)
picogo 里面好像找不到gitee了。

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/XhMFDm5uLCOcmU5JPiI66A
