### ISSUE TITLE
CMake&&VScode基本使用技巧

### ISSUE THREAD

**Issue by xupenghu** [supperthomas/supperthomas_doc#120]
- 使用vscode编辑代码
- 使用cmake管理
- 使用gcc编译

**Comment by xupenghu** [comment]
输出文档，CSND链接在[这里](https://blog.csdn.net/u014421520/article/details/118443417)

**Comment by supperthomas** [comment]
https://www.bilibili.com/video/BV1vR4y1u77h?p=3&spm_id_from=pageDriver

**Comment by supperthomas** [comment]
ADD_SUBDIRECTORY

语法 : ADD_SUBDIRECTORY(NAME) 添加一个文件夹进行编译，该文件夹下的 CMakeLists.txt 负责编译该文件夹下的源码. NAME是想对于调用add_subdirectory的CMakeListst.txt的相对路径．

**Comment by supperthomas** [comment]
cmake教程
https://mp.weixin.qq.com/s/GTL9iXVgTH5imnevW1qu2Q

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s?__biz=MzU5MzcyMjI4MA==&mid=2247505251&idx=2&sn=bddcc7c850dfae7c783585926b32ab56&chksm=fe0ebba4c97932b23af390dbb7a779afa9aa502122cecc04d6ead05f0f7a8175d221b8ccb431&scene=21#wechat_redirect
