### ISSUE TITLE
【RT-Thread社区活动】工作情况记录

### ISSUE THREAD

**Issue by chenyingchun0312** [supperthomas/supperthomas_doc#165]
[RT-Thread贡献活动悬赏列表](https://docs.qq.com/sheet/DS1Znd2hVSEVrQ3NR?tab=boq7ae)

| 任务ID | 任务内容                 | 积分 | 参考链接                                                     | 完成情况 |
| ------ | ------------------------ | ---- | ------------------------------------------------------------ | -------- |
| 1      | completion.c 函数注释    | 8    | https://club.rt-thread.org/ask/article/2500.html<br />https://github.com/RT-Thread/rt-thread/pull/4943 | 完成     |
| 2      | completion.c函数使用方法 | 20   | https://gitee.com/rtthread/docs-online/pulls/168             | 完成     |
| 15     | risc-v移植               | 50   | https://gitee.com/rtthread/docs-online/pulls/184             | 完成     |
| 25     | studio基于芯片创建工程   | 20   | https://gitee.com/rtthread/docs-online/pulls/177             | 完成     |
| 21     | Ymodem使用               | 20   |                                                              |     以后再做     |
| 24     | usbd cdc的使用           | 20   | https://gitee.com/rtthread/docs-online/pulls/183             | 完成     |

**Comment by supperthomas** [comment]
TO 9.10

**Comment by chenyingchun0312** [comment]
希望大家一起参与，完善RISC-V内核移植文档

https://club.rt-thread.org/ask/question/432771.html
