### ISSUE TITLE
【rtt usb软件包】尝试把tinyusb或者其他usb stack做成rtt 软件包

### ISSUE THREAD

**Issue by chenyingchun0312** [supperthomas/supperthomas_doc#169]

**Comment by chenyingchun0312** [comment]
https://github.com/RT-Thread/rt-thread/issues/4776

**Comment by chenyingchun0312** [comment]
rt-thread 代码中，加入tinyusb以及相关nrf52840 移植文件后，可以USB CDC可以正常枚举

接下来研究下原理，然后思考如何将tinyusb做成rt-thread的软件包

![image](https://user-images.githubusercontent.com/44871523/135631718-647f7df3-ff51-4ed0-b839-014e8b136495.png)

**Comment by chenyingchun0312** [comment]
tinyusb KEIL 工程：

https://github.com/NikitaKhalyavin/tinyusb_stm32f103_test_in_keil

https://github.com/nickfox-taterli/tinyusb_stm32f769disco

**Comment by chenyingchun0312** [comment]
测试分支： https://github.com/chenyingchun0312/rt-thread/tree/nrfx_usbd

需要继续优化

**Comment by chenyingchun0312** [comment]
![image](https://user-images.githubusercontent.com/44871523/135720607-3588f25d-69a7-4ea6-8a94-6b770e4e46fe.png)

**Comment by chenyingchun0312** [comment]
tinyusb使用记录

https://mp.weixin.qq.com/s/obowqT02b866YaeWlQWr2g

**Comment by chenyingchun0312** [comment]
https://github.com/hathach/tinyusb/discussions/731

**Comment by chenyingchun0312** [comment]
目前STM32适配工作基本完成，接着，我这边再把nfr5x适配好

**Comment by chenyingchun0312** [comment]
nrf5x usb，目前的阶段，先这样吧。

已完成tinyusb2rtt部分移植，还需要优化
https://github.com/chenyingchun0312/packages/tree/dev_tinyusb
https://github.com/chenyingchun0312/tinyusb2rtt
https://github.com/chenyingchun0312/rt-thread/tree/tinyusb2rtt

状态
nodric 52840 usbd cdc 设备/audio 设备 枚举正常，menuconfig配置

**Comment by supperthomas** [comment]
有计划PR到upstream吗？
