### ISSUE TITLE
【MindManager】使用，学习

### ISSUE THREAD

**Issue by chenyingchun0312** [supperthomas/supperthomas_doc#174]
[MindManager](https://www.mindmanager.cn/xiazai.html)

**Comment by chenyingchun0312** [comment]
暂时还没有找到合适的pojie方式

**Comment by chenyingchun0312** [comment]
使用Xmind替代，感觉也不错[xMind](https://mp.weixin.qq.com/s?__biz=MzA4MjU4MTg2Ng==&mid=2247491860&idx=4&sn=7178c31922a7cde043e5ba264fe69a1f&chksm=9f812111a8f6a807def936dc864ed6e2ce590eb763d13498e950fd0cbeeb0606d88d96325de6&scene=21#wechat_redirect)

**Comment by supperthomas** [comment]
https://www.zhihu.com/question/68487405
