### ISSUE TITLE
MATTER

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#179]
调研一下matter协议栈

**Comment by supperthomas** [comment]
https://buildwithmatter.com/

**Comment by supperthomas** [comment]
https://github.com/project-chip/connectedhomeip

**Comment by supperthomas** [comment]
https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/nrfconnect

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/agdd0OdIba5QiNtcrFtL4A

**Comment by supperthomas** [comment]
https://zhuanlan.zhihu.com/p/456295773

**Comment by supperthomas** [comment]
User guide
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md

**Comment by supperthomas** [comment]
Esp32 c3
https://github.com/project-chip/connectedhomeip/tree/master/examples/all-clusters-app/esp32

**Comment by supperthomas** [comment]
```
--flash_mode dio --flash_freq 80m --flash_size 4MB
0x0 bootloader/bootloader.bin
0x20000 chip-all-clusters-app.bin
0x8000 partition_table/partition-table.bin
0xf000 ota_data_initial.bin
```

[firmware.zip](https://github.com/supperthomas/supperthomas_doc/files/8376611/firmware.zip)

**Comment by supperthomas** [comment]
TBD

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/7LcnUBkn3VkRnXgNqwVBAw

**Comment by balanceTWK** [comment]
https://github.com/project-chip/connectedhomeip

**Comment by supperthomas** [comment]
乐鑫matter

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/7FChuO3ldS9M5wQErQpONw

**Comment by supperthomas** [comment]
https://zhuanlan.zhihu.com/p/580325731?utm_psn=1571875736297857025&utm_id=0

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/Ykj50pZvEYr3COUsGLyCpg

**Comment by supperthomas** [comment]
matter教程
https://www.zhihu.com/people/niu-pi-tang-23-70/posts

**Comment by supperthomas** [comment]
nrf52840 dongle FIRMWARE如何制作
https://www.youtube.com/watch?v=xCyzNzYSG4U

**Comment by supperthomas** [comment]
https://github.com/project-chip/connectedhomeip/tree/master/src/platform

**Comment by supperthomas** [comment]
https://club.rt-thread.org/ask/article/8c92f58a958feeb1.html
https://club.rt-thread.org/ask/article/ab47d2a6e76dc7ae.html
https://club.rt-thread.org/ask/article/b0846ab64046abde.html
