### ISSUE TITLE
[NRFX LOG] 如何在nrfx驱动中，使能LOG打印

### ISSUE THREAD

**Issue by chenyingchun0312** [supperthomas/supperthomas_doc#199]
![image](https://user-images.githubusercontent.com/44871523/134812717-74505355-a7d9-4b53-880d-b58dbbf9c904.png)

预处理，发现：比如针对nrfx_usbd.c的处理中 NRF_LOG_LEVEL 定义成了0，导致预处理，即忽略了打印
![image](https://user-images.githubusercontent.com/44871523/134812742-6dbd79d7-d34d-40c4-9c9f-cf909ed0e518.png)

暂且，如下处理，可以打印出来：
![image](https://user-images.githubusercontent.com/44871523/134812790-22c1cfd8-3280-4b43-9fbf-eff76f4ce180.png)

**Comment by supperthomas** [comment]
@chenyingchun0312 【青风带你学蓝牙5.0视频教程（nrf52832开发教程/nrf52840开发教程）-哔哩哔哩】https://b23.tv/dgEeuS

**Comment by chenyingchun0312** [comment]
经过分析，如下代码，找到解决问题的方法

![image](https://user-images.githubusercontent.com/44871523/134922776-59532906-eb81-4ab3-8b60-411f2167ddbd.png)


其实就是将如下宏，配置成1，然后设置想要的日志level即可
![image](https://user-images.githubusercontent.com/44871523/134922701-ef2e6fd3-1efa-4f8e-acf2-827bc80f0c3a.png)
