### ISSUE TITLE
[nimble][nordic]同步到最新的代码

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#241]

**Comment by hyhkjiy** [comment]
[使用Newt在nRF52832上运行NimBLE](https://jiy.notion.site/Newt-nRF52832-NimBLE-3f0f3fa0d28a4d608b53211a4be73ca4)

**Comment by hyhkjiy** [comment]
https://github.com/RT-Thread-packages/nimble/issues/11

**Comment by supperthomas** [comment]
https://github.com/RT-Thread-packages/nimble/issues/14
