### ISSUE TITLE
远程调试

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#319]
JLINK 远程调试
https://www.segger.com/products/debug-probes/j-link/tools/j-link-remote-server/

platform-io 

https://docs.platformio.org/en/latest/plus/pio-remote.html

vscode remote 

https://www.jianshu.com/p/1298f4ee6ef7?utm_campaign=haruki&utm_content=note&utm_medium=reader_share&utm_source=weixin

**Comment by chenyingchun0312** [comment]
[如何使用J-Link远程调试？](https://mp.weixin.qq.com/s/uhGrIbAPmYxa_H2PHWf6SQ)

**Comment by supperthomas** [comment]
【KEIL】【JLINK】如何在世界任何地方进行KEIL JLINK调试！
https://club.rt-thread.org/ask/article/39471af99e5208dc.html
