### ISSUE TITLE
[小工具]windows截图小工具

### ISSUE THREAD

**Issue by chenyingchun0312** [supperthomas/supperthomas_doc#332]
微信和QQ的截图平常用的挺多的，但是有时，上班的时候，微信,QQ太多，想专心工作不被打扰，因此不想登录，不登陆的话，截图功能就用不了了，QQ截图有一个特色，支持长截图，这里安利最近刚发现的一款截图软件

[snipaste 软件下载](https://zh.snipaste.com/)
[软件使用](https://docs.snipaste.com/zh-cn/pro) 

试用了一下，感觉很不错，除了没有看到支持长截图以外，其他都很nice

**Comment by supperthomas** [comment]
使用教程：
按F1 即可截图

https://docs.snipaste.com/zh-cn/getting-started

**Comment by chenyingchun0312** [comment]
不需要登陆QQ，就可以使用QQ截图的所有功能

https://mp.weixin.qq.com/s/X5DjLPLksOPFh16_ad_CHQ
