### ISSUE TITLE
C语言 写代码编码规范 MISRA

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#354]
- [ ] MISRA   https://www.synopsys.com/zh-cn/automotive/what-is-misra.html
- [ ]

**Comment by supperthomas** [comment]
汽车行业 C 语言标准：MISRA C

https://mp.weixin.qq.com/s/xhpNL0JD_xWsjaLKRiIm_w

**Comment by supperthomas** [comment]
在线验证工具
https://pclintplus.com/gmp/demo/

**Comment by supperthomas** [comment]
pc-lint 工具可以检测MISRA

**Comment by supperthomas** [comment]
MISRA C：2012 又是什么标准？


https://mp.weixin.qq.com/s/rzn7ODK5gd9IxSoeT0vsOQ

**Comment by supperthomas** [comment]
https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html

**Comment by supperthomas** [comment]
https://gitlab.com/MISRA/MISRA-C/MISRA-C-2012/Example-Suite/-/tree/master

**Comment by wangwenqiangGitHub** [comment]
有MISAR-c-2012的中文版本么

**Comment by supperthomas** [comment]
https://github.com/nasa/cFS/blob/main/.github/workflows/static-analysis-misra.yml

MISRA 静态检查
