### ISSUE TITLE
mesh这里的通讲是有问题的

### ISSUE THREAD

**Issue by lym555** [supperthomas/supperthomas_doc#356]
mesh的承载层是分为GATT和广播承载层的，绝大数都是支持GATT承载层的，他是基于连接情况下，而广播承载层，需满足被动扫描的情况下还要能开启广播，这个一般设备不具备，和你的描述正好相反，而且对于mesh的架构虽然他是基于ble core协议来的，但是他不能建立在core协议的组件上，有些东西是相耦合的，比如GAP就不能这么画，GAP是直达HCI的，和mesh的承载层是相藕的

**Comment by supperthomas** [comment]
欢迎pr一些东西上来

**Comment by supperthomas** [comment]
这个是很早写的。初学者肯定有些东西理解的不是很透彻，感谢指正。也欢迎在论坛里分享一些文档
http://club.rt-thread.org/invite/13897
