### ISSUE TITLE
西游翻墙

### ISSUE THREAD

**Issue by bobwenstudy** [supperthomas/supperthomas_doc#363]
https://xiyou4you.us/r/?s=19672149

**Comment by supperthomas** [comment]
![图片](https://user-images.githubusercontent.com/60349489/184158389-06613399-8930-4aec-8d60-0d8a8331d90d.png)

**Comment by supperthomas** [comment]
![图片](https://user-images.githubusercontent.com/60349489/184158464-dbc737de-9fb2-4b9f-aafa-0bfd0cdb7d98.png)
