### ISSUE TITLE
基于 ARMV7M 架构特性，设计的内存监控组件。

### ISSUE THREAD

**Issue by balanceTWK** [supperthomas/supperthomas_doc#365]
https://github.com/balanceTWK/armv7m_DWT

参考文档：
[Arm®v7-M Architecture Reference Manual.pdf](https://github.com/supperthomas/supperthomas_doc/files/9278364/Arm.v7-M.Architecture.Reference.Manual.pdf)

**Comment by supperthomas** [comment]
可以论坛里搞个文档介绍一下~~
