### ISSUE TITLE
功耗测试仪推荐

### ISSUE THREAD

**Issue by xupenghu** [supperthomas/supperthomas_doc#378]
1. [正点原子PT100](https://detail.tmall.com/item.htm?spm=a230r.1.14.6.43027ebfEfQ6gD&id=676139724711&ns=1&abbucket=19)
2. [合宙IoT Power](https://zhuanlan.zhihu.com/p/429295076)

**Comment by xupenghu** [comment]
合宙IoT Power

https://user-images.githubusercontent.com/28744220/185749361-9d4450d2-cb6d-4b77-a9b4-d61a553ae574.mp4

**Comment by hyhkjiy** [comment]
[英加 EMK850](https://item.taobao.com/item.htm?spm=a230r.1.14.3.3ad7481bQldjnH&id=627426307602&ns=1&abbucket=18#detail)

**Comment by supperthomas** [comment]
https://oshwhub.com/micespring/handcon
