### ISSUE TITLE
任务六，测一下nordic bsp上的所有驱动外设

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#385]
目前RT-THREAD更新了新版本，尝试在bsp上想一个能够快速测试所有驱动外设的方法。
可以先简单写写思路
- [ ]

**Comment by chenyingchun0312** [comment]
快速验证所有驱动，可以试试UTEST，但是还是无法避免需要使用实际的测试子板，所以外设驱动，是需要硬件配合的，可能也不是那种，可以一蹴而就的。

我这边计划从下周开始，陆续把所有驱动外设验证一下，使用nordic nrf52832和nrf52840开发板 验证驱动

- [ ] GPIO
- [ ] UART
- [ ] I2C
- [ ] SPI
- [ ] WDT
- [ ] TIMER
- [ ] RTC
- [ ] ADC
- [ ] QSPI   不太熟
- [ ] UARTE 不太熟

**Comment by supperthomas** [comment]
陈工：不用着急先做，可以先构思构思，还有一些特殊外设，计划怎么测~比如SPI I2C。 如果后续我们能整理出一份测试文档，给让后面人照着文档能顺利测试成功，也是比较有意义的。

**Comment by supperthomas** [comment]
https://mp.weixin.qq.com/s/ZWeKH53D1XOBB6zQpvaRug
