### ISSUE TITLE
[doc][OTA] mcuboot 

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#83]
介绍和使用mcuboot，并看是否可以做成软件包。

**Comment by supperthomas** [comment]
https://github.com/mcu-tools/mcuboot

**Comment by lt6210925** [comment]
1. 为什么需要MCUBOOT
2. MCUBOOT有哪些功能
3. mcuboot如何使用起来
4. mcuboot有哪些优势。

**Comment by lt6210925** [comment]
1. bin和烧入的FLASH中的bin是否一样？

**Comment by supperthomas** [comment]
1. BootLoader传输流程。

**Comment by supperthomas** [comment]
1. 搭建zephyr环境，基于nrf52环境

**Comment by supperthomas** [comment]
1. 烧写SLOT1成功，但是SLOT2好像不起作用，

**Comment by lt6210925** [comment]
https://interrupt.memfault.com/blog/mcuboot-overview?query=from%20zero%20to%20main

**Comment by supperthomas** [comment]
mcuboot  并不支持hex文件下载，只支持bin文件下载，这个也是一个缺陷，这样会导致bin文件过大。

**Comment by supperthomas** [comment]
https://blog.csdn.net/lt6210925/article/details/119519261
