### ISSUE TITLE
[NORDIC][BSP][RTTHREAD] 让开发板nrf5x支持RTT-STUDIO 

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#95]

**Comment by supperthomas** [comment]
https://club.rt-thread.org/ask/article/2299.html

**Comment by supperthomas** [comment]
@chenyingchun0312

**Comment by chenyingchun0312** [comment]
https://club.rt-thread.org/ask/article/927d249dba33010e.html
https://club.rt-thread.org/ask/article/8c7ef6307a5af301.html
https://club.rt-thread.org/ask/article/e7e7a0fc1ceb1372.html

**Comment by supperthomas** [comment]
RTT-STUDIO 导入最新的BSP-以nRF5x为例
https://club.rt-thread.org/ask/article/f6b897a0f627ec3d.html
